from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field, model_validator


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class AgentStatus(str, Enum):
    SUCCESS = "success"
    ERROR = "error"
    SKIPPED = "skipped"


class FileOperation(str, Enum):
    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"


class FeatureRequest(BaseModel):
    title: str
    description: str
    module_name: str | None = None
    api_prefix: str = "/api/v1"
    entities: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)


class EndpointSpec(BaseModel):
    method: str
    path: str
    summary: str
    requires_auth: bool = True


class UseCaseSpec(BaseModel):
    name: str
    description: str


class ArchitectureModule(BaseModel):
    name: str
    description: str
    entities: list[str]
    use_cases: list[UseCaseSpec]
    endpoints: list[EndpointSpec]


class ArchitecturePlan(BaseModel):
    style: str = "DDD + Clean Architecture"
    feature: FeatureRequest
    modules: list[ArchitectureModule]
    events: list[str] = Field(default_factory=list)
    policies: list[str] = Field(default_factory=list)


class FileArtifact(BaseModel):
    path: str
    content: str = ""
    operation: FileOperation = FileOperation.CREATE


class GeneratedProject(BaseModel):
    root_path: str
    files: list[FileArtifact]


class FileWriteResult(BaseModel):
    root_path: str
    dry_run: bool
    written_files: list[str] = Field(default_factory=list)
    deleted_files: list[str] = Field(default_factory=list)
    created_files: list[str] = Field(default_factory=list)
    updated_files: list[str] = Field(default_factory=list)
    unchanged_files: list[str] = Field(default_factory=list)


class SecurityFinding(BaseModel):
    severity: str
    title: str
    details: str
    file_path: str | None = None
    recommendation: str


class SecurityReport(BaseModel):
    status: str
    findings: list[SecurityFinding] = Field(default_factory=list)
    checks: list[str] = Field(default_factory=list)


class RefactorSuggestion(BaseModel):
    title: str
    details: str
    diff: str


class RefactorReport(BaseModel):
    duplication_ratio: float
    suggestions: list[RefactorSuggestion] = Field(default_factory=list)


class QASummary(BaseModel):
    passed: bool
    coverage_percent: float
    command: str
    stdout: str
    stderr: str
    tests_generated: int


class GitOperationResult(BaseModel):
    performed: bool
    branch: str | None = None
    commit_sha: str | None = None
    pr_url: str | None = None
    reason: str | None = None


class AgentLogEntry(BaseModel):
    timestamp: datetime = Field(default_factory=utc_now)
    correlation_id: str
    agent_name: str
    level: str
    message: str
    payload: dict[str, Any] = Field(default_factory=dict)


class AgentResult(BaseModel):
    agent_name: str
    status: AgentStatus
    payload: dict[str, Any] = Field(default_factory=dict)
    artifacts: list[FileArtifact] = Field(default_factory=list)
    logs: list[AgentLogEntry] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=utc_now)
    finished_at: datetime = Field(default_factory=utc_now)


class PipelineStep(BaseModel):
    name: str
    agent: str
    continue_on_error: bool = False
    enabled: bool = True
    retries: int = 0
    retry_backoff_seconds: float = 0.25
    timeout_seconds: float | None = None
    config: dict[str, Any] = Field(default_factory=dict)


class PipelineDefinition(BaseModel):
    name: str
    steps: list[PipelineStep]


class GitConfig(BaseModel):
    enabled: bool = False
    auto_commit: bool = False
    auto_pr: bool = False
    repo: str | None = None
    base_branch: str = "main"
    branch_prefix: str = "coreflow"
    commit_message: str = "chore(coreflow): generate feature artifacts"
    pr_title: str = "CoreFlow generated feature"
    pr_body: str = "Automated feature delivery generated by CoreFlow Agents."


class RunRequest(BaseModel):
    request: FeatureRequest
    pipeline_name: str = "default"
    target_root: str = "generated"
    dry_run: bool = False
    git: GitConfig = Field(default_factory=GitConfig)
    provider: str = "template"
    correlation_id: str | None = None


class ExecutionContext(BaseModel):
    correlation_id: str = Field(default_factory=lambda: str(uuid4()))
    request: FeatureRequest
    target_root: str
    dry_run: bool = False
    git: GitConfig = Field(default_factory=GitConfig)
    state: dict[str, Any] = Field(default_factory=dict)
    agent_results: dict[str, AgentResult] = Field(default_factory=dict)
    execution_logs: list[AgentLogEntry] = Field(default_factory=list)

    @model_validator(mode="after")
    def ensure_target_root(self) -> "ExecutionContext":
        if not self.target_root:
            raise ValueError("target_root cannot be empty")
        return self


class ExecutionSummary(BaseModel):
    correlation_id: str
    status: AgentStatus
    pipeline: str
    request: FeatureRequest
    results: dict[str, AgentResult]
    artifacts_root: str
    logs: list[AgentLogEntry]
    git: GitOperationResult | None = None


class ExecutionStatusResponse(BaseModel):
    correlation_id: str
    status: str
    summary: ExecutionSummary | None = None
