from __future__ import annotations

import asyncio
import re
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

from agents.base import BaseAgent
from domain.models import AgentResult, AgentStatus, ArchitecturePlan, ExecutionContext, FileArtifact, QASummary
from domain.services import slugify


class QAAgent(BaseAgent):
    name = "qa"
    required_state_keys = ("architect", "backend")

    def __init__(self, logger, file_manager, minimum_coverage: int = 85):
        super().__init__(logger)
        self.file_manager = file_manager
        self.minimum_coverage = minimum_coverage

    async def _execute(self, context: ExecutionContext) -> AgentResult:
        plan = ArchitecturePlan.model_validate(context.state["architect"]["architecture"])
        project_root = Path(context.state["backend"]["project_root"])
        module_name = slugify(plan.modules[0].name)
        entity_name = plan.modules[0].entities[0]
        test_artifact = FileArtifact(
            path="tests/test_api.py",
            content=self._test_content(plan.feature.api_prefix.rstrip("/"), module_name, entity_name),
        )
        await asyncio.to_thread(self.file_manager.apply, str(project_root), [test_artifact], context.dry_run)

        if context.dry_run:
            summary = QASummary(
                passed=True,
                coverage_percent=100.0,
                command="dry-run",
                stdout="Dry run enabled; coverage execution skipped.",
                stderr="",
                tests_generated=1,
            )
        else:
            summary = await asyncio.to_thread(self._run_tests, project_root)
            if not summary.passed:
                return AgentResult(
                    agent_name=self.name,
                    status=AgentStatus.ERROR,
                    payload={"qa_summary": summary.model_dump(mode="json")},
                    artifacts=[test_artifact],
                    errors=["Coverage gate failed."],
                )

        return AgentResult(
            agent_name=self.name,
            status=AgentStatus.SUCCESS,
            payload={"qa_summary": summary.model_dump(mode="json")},
            artifacts=[test_artifact],
        )

    def _run_tests(self, project_root: Path) -> QASummary:
        command = [
            sys.executable,
            "-m",
            "pytest",
            "--cov=app",
            f"--cov-fail-under={self.minimum_coverage}",
            "tests",
            "-q",
        ]
        completed = subprocess.run(command, cwd=project_root, capture_output=True, text=True, check=False)
        coverage = self._extract_coverage(completed.stdout + "\n" + completed.stderr)
        return QASummary(
            passed=completed.returncode == 0,
            coverage_percent=coverage,
            command=" ".join(command),
            stdout=completed.stdout,
            stderr=completed.stderr,
            tests_generated=1,
        )

    def _extract_coverage(self, output: str) -> float:
        match = re.search(r"TOTAL\s+\d+\s+\d+\s+(\d+)%", output)
        if match:
            return float(match.group(1))
        return 0.0

    def _test_content(self, api_prefix: str, module_name: str, entity_name: str) -> str:
        return dedent(
            f"""
            from fastapi.testclient import TestClient

            from app.main import app

            client = TestClient(app)
            AUTH_HEADER = {{"Authorization": "Bearer local-token"}}


            def test_root_healthcheck():
                response = client.get("/health")
                assert response.status_code == 200
                assert response.json()["status"] == "ok"


            def test_feature_healthcheck():
                response = client.get("{api_prefix}/{module_name}/health")
                assert response.status_code == 200
                assert response.json()["service"] == "{module_name}"


            def test_routes_require_authentication():
                response = client.get("{api_prefix}/{module_name}")
                assert response.status_code == 401


            def test_create_and_list_{module_name}():
                create_response = client.post(
                    "{api_prefix}/{module_name}",
                    json={{"name": "Primary {entity_name}", "description": "Generated by CoreFlow"}},
                    headers=AUTH_HEADER,
                )
                assert create_response.status_code == 200
                list_response = client.get("{api_prefix}/{module_name}", headers=AUTH_HEADER)
                assert list_response.status_code == 200
                items = list_response.json()
                assert len(items) == 1
                assert items[0]["name"] == "Primary {entity_name}"
            """
        ).strip() + "\n"
